CREATE SCHEMA IF NOT EXISTS siakad_uts;
CREATE TABLE IF NOT EXISTS siakad_uts.users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 email TEXT NOT NULL,
 password TEXT NOT NULL,
 role TEXT NOT NULL CHECK (role IN ('admin','mahasiswa'))
);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_unique ON siakad_uts.users (lower(email));
CREATE TABLE IF NOT EXISTS siakad_uts.students (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL UNIQUE REFERENCES siakad_uts.users(id),
 nim VARCHAR(12) NOT NULL UNIQUE CHECK (nim ~ '^[0-9]{12}$'),
 nama TEXT NOT NULL CHECK (length(trim(nama))>0),
 prodi TEXT NOT NULL CHECK (length(trim(prodi))>0),
 angkatan INTEGER NOT NULL CHECK (angkatan BETWEEN 1000 AND 9999),
 ipk_terakhir NUMERIC(3,2) CHECK (ipk_terakhir BETWEEN 0 AND 4),
 deleted_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS students_active_idx ON siakad_uts.students(id) WHERE deleted_at IS NULL;
CREATE TABLE IF NOT EXISTS siakad_uts.courses (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 kode_mk TEXT NOT NULL UNIQUE,
 nama_mk TEXT NOT NULL,
 sks INTEGER NOT NULL CHECK (sks>0),
 semester INTEGER NOT NULL CHECK (semester>0),
 kuota INTEGER NOT NULL CHECK (kuota>=0)
);
CREATE TABLE IF NOT EXISTS siakad_uts.enrollments (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 student_id BIGINT NOT NULL REFERENCES siakad_uts.students(id),
 course_id BIGINT NOT NULL REFERENCES siakad_uts.courses(id),
 tahun_akademik TEXT NOT NULL CHECK (tahun_akademik ~ '^[0-9]{4}/[0-9]{4}-(Ganjil|Genap)$'),
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 UNIQUE (student_id,course_id,tahun_akademik)
);
CREATE INDEX IF NOT EXISTS enrollments_course_idx ON siakad_uts.enrollments(course_id);
CREATE INDEX IF NOT EXISTS enrollments_student_year_idx ON siakad_uts.enrollments(student_id,tahun_akademik);
